#!/bin/bash

# `helpme` opens interactive search with fzf
# `helpme $1 $2` opens subjects/$1/$2.md, $2 defaults to 'help' if not provided

VIM=${HELPME_EDITOR:-vim}
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"


if [ -n "$1" ]; then
    case "$1" in
        -h|--h|--help|help)
            echo -e "Usage: helpme [subject] [file]"
            echo -e "\t- [subject] and [file] are optional"
            echo -e "\t- [subject] defines the subject under helpme/subjects/"
            echo -e "\t- [file] defines the file under that subject, defaults to help (.md is assumed)"
            exit 0
    esac

    subject="$1"
    filename="help"

    if [ -n "$2" ]; then
        filename="$2"
    fi

    filepath="$SCRIPT_DIR/subjects/$subject/$filename.md"
    if [ -f "$filepath" ]; then
        "$VIM" "$filepath"
    else
        echo "$filepath not found"
    fi
else
    filepath=$(find "$SCRIPT_DIR/subjects" -name '*.md' | fzf --prompt="Select file: ")
    [[ -n "$filepath" ]] && "$VIM" "$filepath"
fi

