#!/usr/bin/env bash

# --- INFO --- #
# `tidbit` opens interactive search with fzf
# `tidbit $1 $2` opens subjects/$1/$2.md, $2 defaults to 'tidbit'
# --- --- #

# --- Variables --- #
editor=${TIDBIT_EDITOR:-vim}
script_dir="$(cd "$(dirname "$0")" && pwd)"
# --- --- #

# --- Helper functions --- #
handle_help() {
    arg1=$(printf '%s' "$1" | tr '[:upper:]' '[:lower:]')
    case "${arg1}" in
        -h|--h|--help|help)
            printf "Usage: tidbit [subject] [file]\n"
            printf "\t- [subject] and [file] are optional\n"
            printf "\t- [subject] specifies the subject under tidbit/subjects/\n"
            printf "\t- [file] specifies the file under that subject, defaults to tidbit (.md is assumed)\n"
            exit 0
    esac
}

validate_arg_count() {
    if [ "$#" -gt 2 ]; then
        printf "Too many arguments\n"
        handle_help help
    fi
}
# --- --- #

# --- Main --- #
main() {
    validate_arg_count "$@"
    handle_help "$1"

    if [ -n "$1" ]; then
        subject="$1"
        filename="${2:-tidbit}"
        filepath="$script_dir/subjects/$subject/$filename.md"

        if [ -f "$filepath" ]; then
            "$editor" "$filepath"
        else
            read -rp "$filepath not found, create it now? [y/n] " ans
            ans=${ans:-y} # default to y on enter pressed
            ans=$(printf '%s' "$ans" | tr '[:upper:]' '[:lower:]')
            if [ "${ans}" == "y" ] || [ "${ans}" == "yes" ]; then
                mkdir -p "$(dirname -- "$filepath")" && touch -- "$filepath"
                "$editor" "$filepath"
            fi
        fi
    else
        filepath=$(find "$script_dir/subjects" -name '*.md' | fzf --prompt="Select file: ")
        if [ -n "$filepath" ]; then
            "$editor" "$filepath"
        fi
    fi
}
# --- --- #

# --- Entrypoint --- #
main "$@"

