#!/bin/bash

# --- INFO --- #
# `tidbit` opens interactive search with fzf
# `tidbit $1 $2` opens subjects/$1/$2.md, $2 defaults to 'tidbit'
# --- --- #

# --- Variables --- #
editor=${TIDBIT_EDITOR:-vim}
script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# --- --- #

# --- Helper functions --- #
# Handles any help request
handle_help() {
    case "${1,,}" in
        -h|--h|--help|help)
            echo -e "Usage: tidbit [subject] [file]"
            echo -e "\t- [subject] and [file] are optional"
            echo -e "\t- [subject] defines the subject under tidbit/subjects/"
            echo -e "\t- [file] defines the file under that subject, defaults to tidbit (.md is assumed)"
            exit 0
    esac
}

# Checks for too many arguments
validate_arg_count() {
    if [ "$#" -gt 2 ]; then
        echo "Too many arguments"
        handle_help help
    fi
}
# --- --- #

# --- Main --- #
main() {
    validate_arg_count "$@"
    handle_help "$1"

    if [ -n "$1" ]; then
        subject="$1"
        filename="${2:-tidbit}"
        filepath="$script_dir/subjects/$subject/$filename.md"

        if [ -f "$filepath" ]; then
            "$editor" "$filepath"
        else
            read -rp "$filepath not found, create it now? [y/n] " ans
            ans=${ans:-y}
            if [[ "${ans,,}" == "y" || "${ans,,}" == "yes" ]]; then
                mkdir -p "$(dirname -- "$filepath")" && touch -- "$filepath"
                "$editor" "$filepath"
            fi
        fi
    else
        filepath=$(find "$script_dir/subjects" -name '*.md' | fzf --prompt="Select file: ")
        [[ -n "$filepath" ]] && "$editor" "$filepath"
    fi
}
# --- --- #

# --- Entrypoint --- #
main "$@"

