#!/bin/bash

# --- INFO --- #
# `tidbit` opens interactive search with fzf
# `tidbit $1 $2` opens subjects/$1/$2.$file_extension, $2 defaults to 'tidbit'
# --- --- #

# --- Variables --- #
editor=${TIDBIT_EDITOR:-vim}
script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# --- --- #

# --- Helper functions --- #
# load_config() {
#     . "$script_dir/.tidbitconfig"
#
#     # Fallback defaults
#     ${editor:-vim}
#     ${file_extension:-md}
#     ${fzf:-fzf}
# }

handle_help() {
    case "${1,,}" in
        -h|--h|--help|help)
            echo -e "Usage: tidbit [subject] [file]"
            echo -e "\t- [subject] and [file] are optional"
            echo -e "\t- [subject] defines the subject under tidbit/subjects/"
            echo -e "\t- [file] defines the file under that subject, defaults to tidbit (.$file_extension is assumed)"
            exit 0
    esac
}

handle_config_edit() {
    if [[ "$#" -eq 1 && "$1" == "config" ]]; then
        "$editor" "$script_dir/.tidbitconfig"
    fi
}

validate_arg_count() {
    if [ "$#" -gt 2 ]; then
        echo "Too many arguments"
        handle_help help
    fi
}
# --- --- #

# --- Main --- #
main() {
    load_config
    validate_arg_count "$@"
    handle_help "$1"
    handle_config_edit "$@"

    if [ -n "$1" ]; then
        subject="$1"
        filename="${2:-tidbit}"
        filepath="$script_dir/subjects/$subject/$filename.$file_extension"

        if [ -f "$filepath" ]; then
            "$editor" "$filepath"
        else
            read -rp "$filepath not found, create it now? [y/n] " ans
            ans=${ans:-y}
            if [[ "${ans,,}" == "y" || "${ans,,}" == "yes" ]]; then
                mkdir -p "$(dirname -- "$filepath")" && touch -- "$filepath"
                "$editor" "$filepath"
            fi
        fi
    else
        filepath=$(find "$script_dir/subjects" -name '*.file_extension' | fzf --prompt="Select file: ")
        [[ -n "$filepath" ]] && "$editor" "$filepath"
    fi
}
# --- --- #

# --- Entrypoint --- #
main "$@"

